apiVersion: v1
kind: ServiceAccount
metadata:
  name: unload-ingress-sa
  namespace: default
  labels:
    app.kubernetes.io/name: ingress-unload
    app.kubernetes.io/part-of: ingress-unload
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unload-ingress-cr
  labels:
    app.kubernetes.io/name: ingress-unload
    app.kubernetes.io/part-of: ingress-unload
rules:
- apiGroups: [""]
  resources: ["endpoints","pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: unload-ingress-role
  namespace: default
  labels:
    app.kubernetes.io/name: ingress-unload
    app.kubernetes.io/part-of: ingress-unload
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: unload-ingress-rb
  namespace: default
  labels:
    app.kubernetes.io/name: ingress-unload
    app.kubernetes.io/part-of: ingress-unload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unload-ingress-role
subjects:
  - kind: ServiceAccount
    name: unload-ingress-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: unload-ingress-crb
  labels:
    app.kubernetes.io/name: ingress-unload
    app.kubernetes.io/part-of: ingress-unload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unload-ingress-cr
subjects:
  - kind: ServiceAccount
    name: unload-ingress-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unload
  namespace: default
  labels:
    app: unload
spec:
  selector:
    matchLabels:
      app: unload
  template:
    metadata:
      labels:
        app: unload
    spec:
      serviceAccountName: unload-ingress-sa
      containers:
      - name: unload
        image: quay.io/owlwalks/unload
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - name: grpc
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: unload
  namespace: default
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: unload
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 50051
    targetPort: grpc